### ISSUE TITLE
The project in the CWD is not a NativeScript project.

### ISSUE THREAD

**Issue by bagstel** [NativeScript/nativescript-app-sync#70]
Hello everyone!

"**The project in the CWD is not a NativeScript project.**"
I have this error on release an app on windows.

**Comment by tobiasklemp** [comment]
I got the same error on mac and windows. I did a release build and then tried to release it with default parameter.

**Comment by jelledijkstra97** [comment]
Having the same problem. Any solutions?

**Comment by FabianStr** [comment]
Had the same issue after migrating to ns7, fixed it with adding

 `"nativescript": {
  "id": "<appId>",
  "tns-android": {
    "version": "7.0.0"
  },
  "tns-ios": {
    "version": "7.0.0"
  }
},`

in the package.json

**Comment by bagstel** [comment]
> Had the same issue after migrating to ns7, fixed it with adding
> 
> `"nativescript": { "id": "<appId>", "tns-android": { "version": "7.0.0" }, "tns-ios": { "version": "7.0.0" } },`
> 
> in the package.json

**Comment by bagstel** [comment]
> > Had the same issue after migrating to ns7, fixed it with adding
> > `"nativescript": { "id": "<appId>", "tns-android": { "version": "7.0.0" }, "tns-ios": { "version": "7.0.0" } },`
> > in the package.json

Thanks it works

**Comment by bagstel** [comment]
> Had the same issue after migrating to ns7, fixed it with adding
> 
> `"nativescript": { "id": "<appId>", "tns-android": { "version": "7.0.0" }, "tns-ios": { "version": "7.0.0" } },`
> 
> in the package.json

Thanks it works

**Comment by wardourdigital** [comment]
I am trying this on NS8.0.5, same issue. The config has change in v8. Has anyone been able to get this working?

**Comment by alexonozor** [comment]
Any solution to this?
